export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST';
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL';
export const ADMIN_USER_LIST_RESET = 'ADMIN_USER_LIST_RESET';

export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_FAIL = 'ADMIN_DELETE_USER_FAIL';

export const ADMIN_USER_PROFILE_SUCCESS = 'ADMIN_USER_PROFILE_SUCCESS';
export const ADMIN_USER_PROFILE_REQUEST = 'ADMIN_USER_PROFILE_REQUEST';
export const ADMIN_USER_PROFILE_FAIL = 'ADMIN_USER_PROFILE_FAIL';
export const ADMIN_USER_PROFILE_RESET = 'ADMIN_USER_PROFILE_RESET';

export const ADMIN_UPDATE_USER_PROFILE_SUCCESS = 'ADMIN_UPDATE_USER_PROFILE_SUCCESS';
export const ADMIN_UPDATE_USER_PROFILE_REQUEST = 'ADMIN_UPDATE_USER_PROFILE_REQUEST';
export const ADMIN_UPDATE_USER_PROFILE_FAIL = 'ADMIN_UPDATE_USER_PROFILE_FAIL';
export const ADMIN_UPDATE_USER_PROFILE_RESET = 'ADMIN_UPDATE_USER_PROFILE_RESET';
