export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_FETCHED = 'PRODUCT_LIST_FETCHED';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_ITEM_REQUEST = 'PRODUCT_ITEM_REQUEST'
export const PRODUCT_ITEM_FETCHED = 'PRODUCT_ITEM_FETCHED'
export const PRODUCT_ITEM_FAIL = 'PRODUCT_ITEM_FAIL'

export const ADMIN_PRODUCT_DELETE_REQUEST = 'ADMIN_PRODUCT_DELETE_REQUEST'
export const ADMIN_PRODUCT_DELETE_SUCCESS = 'ADMIN_PRODUCT_DELETE_SUCCESS'
export const ADMIN_PRODUCT_DELETE_FAIL = 'ADMIN_PRODUCT_DELETE_FAIL'
