export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_FETCHED = 'PRODUCT_LIST_FETCHED';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_ITEM_REQUEST = 'PRODUCT_ITEM_REQUEST'
export const PRODUCT_ITEM_FETCHED = 'PRODUCT_ITEM_FETCHED'
export const PRODUCT_ITEM_FAIL = 'PRODUCT_ITEM_FAIL'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_FETCHED = 'PRODUCT_CREATE_REVIEW_FETCHED'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'
